### PR TITLE
38 add units location to map

### LINKED ISSUE #38: Add units location to map

### PR DESCRIPTION
**Pull request by eminamuratspahic**
Close #38 
Added functionality to show user location.

When using Map for the first time there should come a question that the user must approve. Can you please confirm that? 

The functionality should be moved out to a context file for more separating of code.

The CSS of the cat should be decided by the group.

### CODE REVIEW

**Review by liinnjohansson — COMMENTED** [review]
I don't know if it is my Samsung that makes life difficult, but I get a warning when I run the code and also can not see the map. 

There is something in the code as well.
In MapScreen I get this, because the import for the context is not there:
error

And this is the warning I get, when I try to run the app
error2

**Comment by EmelieBrobergs** [comment]
Latest commit works fine on my phone, you have seen screen video in chatt. 

Test of code in my Android phone Huawei P30
* Fist time the app asked for permission to use the phone location
* When map-tab is opened first time the map is zoomed in / centred on the cat aka my position
* After clicking round in app and re entered map-tab the map is view is the same as I left it.
* Click on mapIcon for bistros (dark red) make them light color and centred on screen.

image
image

**Comment by EmelieBrobergs** [comment]
Ok

**Comment by eminamuratspahic** [comment]
It was not my intention to delete that code, i have put it back

**Comment by EmelieBrobergs** [comment]
All looks good!

**Review by EmelieBrobergs — APPROVED** [review]

**Pull request merged**
