### PR TITLE
7 create bistro card

### LINKED ISSUE #7: Create Bistro-card
Restrictions: 
Create image and contentbox

Do not include tags and heart

https://callstack.github.io/react-native-paper/card.html

Skärmavbild 2021-09-23 kl  10 48 54

### PR DESCRIPTION
**Pull request by EmelieBrobergs**
close #7 
Issue is completed and tested on ScreenTabOne.tsx

* Rendering on weekday added
* Rendering do not check the week number, see comment

image

### CODE REVIEW

**Review by liinnjohansson — CHANGES_REQUESTED** [review]
I get a warning that I guess has something to do with the Flatlist being inside a ScrollView. 
The design is very good looking. But I have two things to discuss: 
- The title seems to have a bigger padding or margin than the other text-components, do we want them all aligned on the left?
- The boxes have rounded edges. I suppose the component used has a border-radius by default. Something to look at  and fix perhaps?

**Review by liinnjohansson — APPROVED** [review]
Now it looks amazing! Great work!!

**Comment by EmelieBrobergs** [comment]
Refactor code according to comments.

Note. A new issue have to be created for better structure / refactoring of code for determinate what day/week it should look for info to print in this card.

**Comment by liinnjohansson** [comment]
Alright!

**Pull request merged**
