### PR TITLE
18 create menucontent box to menuscreen

### LINKED ISSUE #18: Create menucontent-box to menuscreen
Read address info from data.ts
Fixed box.

**Look how menu-content box will interact to menu-content box**

Skärmavbild 2021-09-23 kl  11 38 44

### PR DESCRIPTION
**Pull request by liinnjohansson**
close #18 

MenuScreen is now displaying components MenuSheet and MenuInfoBox.

When pressing on phone number user will have to choose app to use for phone call. Works perfectly in android (Samsung S7). Haven't tried feature on iOS. 

Hardcoded parts that needs to be altered when navigation is completed:
- Get distance and time it takes to get to the restaurant. 
- Navigation to map when pressing on distance-field in MenuInfoBox.

Styling issue: Can't seem to be able to get the design on MenuSheet right. Please, can someone else have a try at it because this part needs some love, and I have tried to give it (but failed haha).

menu4

### CODE REVIEW

**Review by EmelieBrobergs — CHANGES_REQUESTED** [review]
image

The layout looks good on my phone for the black-box in the bottom.  Some small notes regarding functions:

* Make the mapIcon + text clickable 
* Phone Number: onPress you directs to the phones phone, but to make it more visible in UI please add text decoration underline.
* Rating: Please remove text field and create new issue for this function. Note. This requires updated data interface for Birstor.

**Comment by liinnjohansson** [comment]
Thanks for the input! I completely agree, I'll make those changes ASAP.

**Comment by EmelieBrobergs** [comment]
image

Good changes in UI! Thank you!!

**Comment by EmelieBrobergs** [comment]
One notation thow, the interface Props is optional. You should not be able to visit this screen if no bistro is selected / contains data ? Revis or create new issue to correct is my suggestion.

**Review by EmelieBrobergs — APPROVED** [review]

**Pull request merged**
