### PR TITLE
2 creating togglemenu

### LINKED ISSUE #2: Create togglemenu
Create toggle menu(topbar) and placeholders for "restauranger" and "karta". https://callstack.github.io/react-native-paper/button.html (text-button)

https://callstack.github.io/react-native-paper/appbar-header.html

See Figma for color code

Skärmavbild 2021-09-23 kl  10 25 31

### LINKED ISSUE #5: Create navigation code
Refactor navigation code from start file. Make it more readable.

* Toggle between BistroScreen.tsx and MapScreen.tsx  - SOLVED in prv. issue
* Refactor the interface placement of mention screen above
* Create navigation to Menu, that can be used within screen by sending id

Skärmavbild 2021-09-23 kl  10 25 31
image

### PR DESCRIPTION
**Pull request by eminamuratspahic**
close #2 (**not 5**)

### CODE REVIEW

**Comment by eminamuratspahic** [comment]
Also added this from expo: https://docs.expo.dev/versions/latest/sdk/safe-area-context/

**Review by liinnjohansson — COMMENTED** [review]
Looks good! Only design-issues left, like different color than blue on the tabs.

**Review by liinnjohansson — APPROVED** [review]

**Comment by EmelieBrobergs** [comment]
this line does not look right in index.tsx:
```theme={colorScheme === 'light' ? DarkTheme : DefaultTheme}>```

**Review by EmelieBrobergs — CHANGES_REQUESTED** [review]
see comments in conversation

**Review by EmelieBrobergs — COMMENTED** [review]
The code looks good and working on my phone!

**Review by EmelieBrobergs — APPROVED** [review]

**Pull request merged**
